language: cpp

compiler:
  - gcc

before_install:

install:
  - sudo apt-get install java-1.8.0-openjdk-headless python python-setuptools python-virtualenv libev4-dev libuuid1-dev zlib1g-dev libcurl-dev
  - sudo /usr/bin/easy_install nosexcover mock==1.0.1 gevent pymongo sortedcontainers xmltodict redis

script:
  - make
  - make test

