#language: cpp
language: python
  - "2.7"

#compiler:
#  - gcc

before_install:

install:
  - sudo pip install setuptools nose nosexcover mock==1.0.1 gevent pymongo sortedcontainers xmltodict redis
  - sudo apt-get install g++ cmake openjdk-8-jdk python-pip libev-dev uuid-dev zlib1g-dev
#  - sudo pip install setuptools==36.2.6
#  - sudo easy_install virtualenv
#  - sudo easy_install nose nosexcover mock==1.0.1 gevent pymongo sortedcontainers xmltodict redis

script:
  - which nosetests
  - make
  - make test


