language: cpp

compiler:
  - gcc

before_install:

install:
  - sudo apt-get install openjdk-8-jdk python python-setuptools python-virtualenv libev-dev uuid-dev zlib1g-dev
  - sudo /usr/bin/easy_install nosexcover mock==1.0.1 gevent pymongo sortedcontainers xmltodict redis

script:
  - make
  - make test


